### ISSUE TITLE
Ejercicio # 2 - Punto 2: Que funcion tienen los terminales RST Y CTS en el termina virtual?

### ISSUE THREAD

**Issue by ProgramadorPegasus** [EMTSTISPC/Grupo8#18]

**Comment by evera8** [comment]
2. Que función tienen los terminales RTS y CTS en el terminal virtual?
 
RTS (Solicitud de Envío) – ES UN INDICADOR que puede tener valor 0 o 1, para que el virtual terminal pueda trasmitir tiene que estar configurado en 1 LOGICO.
 
CTS (Libre para Envío) – Es una entrada de Valores que pueden ser 0 o 1 “ENTRADA LOGICA” . Cuando el valor este en 0 virtual terminal no trasmite, pero cuando el valor 1 si trasmite.

 
Ejemplo 1 : Escribi algo en terminal A no va a trasmitir nada a terminal B, porque la entrada lógica CTS esta en 0.

Ejemplo 2: CTS Lógico esta en valor 1 terminal 1, trasmite a terminal B, pero al revés no trasmite 
 
Se agrega pdf a rama de EMILIO VERA con imágenes ilustrativas, nombre en carpeta creada / Practicas I O ../ "Pregunta 2 Terminales RTS Y CTS.pdf"

Anexo link [https://github.com/EMTSTISPC/Grupo8/blob/Emilio-Vera/Pr%C3%A1cticas%20de%20I%20O%20en%20sistemas%20embebidos%20v1.0/Pregunta%202%20Terminales%20RTS%20Y%20CTS.pdf](url)
