### ISSUE TITLE
Ejercicio # 1 - Punto 2: Preguntar Nombre, Apellido, Dirección y celular en mensajes diferentes. Completar las respuestas.

### ISSUE THREAD

**Issue by ProgramadorPegasus** [EMTSTISPC/Grupo8#23]

**Comment by gonaiot** [comment]
@ProgramadorPegasus 
Estimado, esta bien su codigo. Procure utilizar comentarios. A nivel de bloque o linea explican su razon y a nivel general detallan el algoritmo.
