### ISSUE TITLE
Ejercicio # 1 - Punto 5: Ingresar una secuencia de 8 bit por terminal, que activaran los leds correspondientes por el puerto D.

### ISSUE THREAD

**Issue by ProgramadorPegasus** [EMTSTISPC/Grupo8#26]

**Comment by gonaiot** [comment]
@Cabro645 
Estimado Jorge, si bien la implementacion no es la requerida en el ejercicio 1.5, lo resuelve bien. Esta bien documentado su codigo, continue asi.
