### ISSUE TITLE
Ejercicio # 1 - Punto 6: Realizar una función bool cerradura({tipo} clave); que retome true cuando la clave numérica sea 2147483648. Elija el "tipo" de dato apropiadamente. Implemente el circuito que active un relé; Utilice el terminal virtual.

### ISSUE THREAD

**Issue by ProgramadorPegasus** [EMTSTISPC/Grupo8#27]

**Comment by evera8** [comment]
Subo ejercicio 1.6 Practico y simulacion en TinKercad

[https://www.tinkercad.com/things/1yTeoLQCckl-mighty-esboo/editel](url)

// declaro variables
byte rele=2;
String contrasena;

boolean cerradura(String clave){
  if (clave == "2147483648"){
    digitalWrite(2,HIGH);
    return true;
  }else return false;
}

void setup() {
  Serial.begin(9600); // Establezco velocidad de puerto serial
  Serial.println("Bienvenido al Ejercicio 1.6 del TP !! ");
  pinMode (rele, OUTPUT); // Preparo pin para salida
  digitalWrite(rele,LOW); // Incializo en 0 el valor del pin
  
}

void loop()
{
  Serial.println("Ingrese Clave de Cerradura:");
  while (!Serial.available() > 0); // Espero disponibilidad puerto serial
  contrasena = Serial.readStringUntil('\n');
  if (not cerradura(contrasena))
     Serial.println("Cerradura Cerrada!!");
  else 
    Serial.println("Cerradura Abierta!!");
}
![Mighty Esboo](https://user-images.githubusercontent.com/101851669/186273729-9eee1f0d-7ae2-436f-91be-f18261c37746.png)

**Comment by gonaiot** [comment]
@evera8 
Estimado Emilio, esta muy bien su codigo. Bien documentado, continue asi.
