### ISSUE TITLE
Ejercicio 2 e y f

### ISSUE THREAD

**Issue by tecnosisnet** [EMTSTISPC/Grupo8#38]
e)	Que protocolo utilizan los led ws2812? Hay alguna librería para controlarlos con módulos ESP12 o ESP32? Que se podría armar con los WS2812 y porque el fabricante no utilizo protocolos SPI, UART o I2C?
f)	Enumere otros protocolos de comunicación que no sean de campo y descríbalos brevemente

**Comment by evera8** [comment]
Subida en pdf
